# Generated by Django 5.2.4 on 2025-10-07 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="group",
            name="invite_link",
            field=models.CharField(
                blank=True,
                help_text="Optional shareable invite link",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="simplify_debts",
            field=models.BooleanField(
                default=True,
                help_text="Whether to simplify debts using graph algorithms",
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When user joined the group"
            ),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("ADMIN", "Admin"),
                    ("MEMBER", "Member"),
                    ("VIEWER", "Viewer"),
                ],
                default="MEMBER",
                help_text="User's role in the group",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["created_at"], name="groups_grou_created_b17bf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(fields=["type"], name="groups_grou_type_78a730_idx"),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(
                fields=["group", "role"], name="groups_grou_group_i_c169b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(fields=["user"], name="groups_grou_user_id_73c910_idx"),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(
                fields=["created_at"], name="groups_grou_created_86f2a2_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="group",
            table="groups_group",
        ),
        migrations.AlterModelTable(
            name="groupmember",
            table="groups_groupmember",
        ),
    ]
